import type { Metadata } from "next";
import localFont from "next/font/local"; // Fixed the import path
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff", // Path to the font file
  variable: "--font-geist-sans",
  weight: "100 900", // Variable font weight range
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff", // Path to the font file
  variable: "--font-geist-mono",
  weight: "100 900", // Variable font weight range
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
